import {
  faCartShopping,
  faPhone,
  faClipboardList,
  faComments,
} from "@fortawesome/free-solid-svg-icons";

import aboboraCabotia from "./assets/products/abobora_cabotia.jpg";
import aboboraPaulista from "./assets/products/abobora_paulista.png";
import alfaceAmericana from "./assets/products/alface_americana.png";
import batataLavada from "./assets/products/batata_lavada.png";
import couveManteiga from "./assets/products/couve-manteiga.png";
import gengibre from "./assets/products/gengibre.png";

export const tabList = [
  { id: 1, name: "Produtos", icon: faCartShopping },
  // { id: 2, name: "Meus Pedidos", icon: faClipboardList },
  // { id: 3, name: "Como Funciona", icon: faComments },
  // { id: 4, name: "Fale Conosco", icon: faPhone },
];

export const productsList = [
  {
    id: 1,
    name: "Abóbora Cabotia",
    category: "",
    price: 3.99,
    unit: "kg",
    defaultQuantity: 1,
    image: aboboraCabotia,
    stock: 100,
  },
  {
    id: 2,
    name: "Couve Manteiga A CONFIRMAR",
    category: "",
    price: 5.99,
    unit: "kg",
    defaultQuantity: 1,
    image: couveManteiga,
    stock: 100,
  },
  {
    id: 3,
    name: "Abóbora Paulista A CONFIRMAR",
    category: "",
    price: 4.5,
    unit: "cada",
    defaultQuantity: 1,
    image: aboboraPaulista,
    stock: 100,
  },
  {
    id: 4,
    name: "Beterraba",
    category: "",
    price: 4.99,
    unit: "kg",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 5,
    name: "Alface americana",
    category: "",
    price: 3.5,
    unit: "cada",
    defaultQuantity: 1,
    image: alfaceAmericana,
    stock: 100,
  },
  {
    id: 6,
    name: "Rabanete A CONFIRMAR",
    category: "",
    price: 2.8,
    unit: "cada",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 7,
    name: "Gengibre",
    category: "",
    price: 6.99,
    unit: "kg",
    defaultQuantity: 1,
    image: gengibre,
    stock: 100,
  },
  {
    id: 8,
    name: "Alho",
    category: "",
    price: 33.0,
    unit: "kg",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 9,
    name: "Jiló",
    category: "",
    price: 8.99,
    unit: "kg",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 10,
    name: "Batata Lavada/ Escovada",
    category: "",
    price: 4.99,
    unit: "kg",
    defaultQuantity: 1,
    image: batataLavada,
    stock: 100,
  },
  {
    id: 11,
    name: "Mandioquinha A CONFIRMAR A",
    category: "",
    price: 4.99,
    unit: "kg",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 12,
    name: "Mostarda / Catalonia / Almeirao",
    category: "",
    price: 5.99,
    unit: "kg",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 13,
    name: "Cebola",
    category: "",
    price: 3.99,
    unit: "kg",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 14,
    name: "Pimentão Amarelo ou Vermelho",
    category: "",
    price: 15.0,
    unit: "kg",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 15,
    name: "Cebola Roxa",
    category: "",
    price: 7.99,
    unit: "kg",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 16,
    name: "Pimenta Cambuci A CONFIRMAR",
    category: "",
    price: 2.5,
    unit: "cada",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 17,
    name: "Rúcula",
    category: "",
    price: 4.5,
    unit: "cada",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 18,
    name: "Cará",
    category: "",
    price: 7.99,
    unit: "kg",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 19,
    name: "Tomate",
    category: "",
    price: 7.99,
    unit: "kg",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 20,
    name: "Batata Doce Roxa",
    category: "",
    price: 2.99,
    unit: "kg",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 21,
    name: "Quiabo",
    category: "",
    price: 15.0,
    unit: "kg",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 22,
    name: "Batata Doce Branca A CONFIRMAR Pepino Comum",
    category: "",
    price: 4.99,
    unit: "kg",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 23,
    name: "Pepino Japonês",
    category: "",
    price: 8.99,
    unit: "kg",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 24,
    name: "Abobrinha Itália",
    category: "",
    price: 4.99,
    unit: "kg",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 25,
    name: "Cenoura",
    category: "",
    price: 6.99,
    unit: "kg",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 26,
    name: "Milho A CONFIRMAR Pimenta Dedo de Moça",
    category: "",
    price: 18.0,
    unit: "kg",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 27,
    name: "Mandioca c/ Casca",
    category: "",
    price: 3.99,
    unit: "kg",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 28,
    name: "Inhame",
    category: "",
    price: 7.99,
    unit: "kg",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 29,
    name: "Mandioca Descascada A CONFIRMAR Uva Niagara",
    category: "",
    price: 7.99,
    unit: "cumbuca",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 30,
    name: "Pinhão A CONFIRMAR Vagem",
    category: "",
    price: 15.0,
    unit: "kg",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 31,
    name: "Acelga",
    category: "",
    price: 7.0,
    unit: "cada",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 32,
    name: "Brocolis Comum",
    category: "",
    price: 9.99,
    unit: "cada",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 33,
    name: "Caqui chocolate A CONFIRMAR Repolho Branco",
    category: "",
    price: 7.0,
    unit: "cada",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 34,
    name: "Caqui Rama Forte",
    category: "",
    price: 7.99,
    unit: "kg",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 35,
    name: "Espinafre",
    category: "",
    price: 4.5,
    unit: "maço",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 36,
    name: "Morango",
    category: "",
    price: 6.99,
    unit: "cumbuca",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 37,
    name: "Maracujá",
    category: "",
    price: 6.99,
    unit: "kg",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 38,
    name: "Abacaxi Perola",
    category: "",
    price: 6.0,
    unit: "cada",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 39,
    name: "Melancia Baby",
    category: "",
    price: 10.0,
    unit: "cada",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 40,
    name: "Ponkan",
    category: "",
    price: 0.99,
    unit: "kg",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 41,
    name: "Polpas Goiaba/Morango ou Pitaya",
    category: "",
    price: 5.0,
    unit: "cada",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 42,
    name: "Banana Prata",
    category: "",
    price: 6.99,
    unit: "kg",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 43,
    name: "Polpa/ Maracujá",
    category: "",
    price: 5.0,
    unit: "pote",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 44,
    name: "Banana Nanica",
    category: "",
    price: 4.99,
    unit: "kg",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 45,
    name: "Melão",
    category: "",
    price: 6.0,
    unit: "cada",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 46,
    name: "Coco Seco",
    category: "",
    price: 5.99,
    unit: "kg",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 47,
    name: "Figo Roxo",
    category: "",
    price: 10.0,
    unit: "cumbuca",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 48,
    name: "Coco Verde A CONFIRMAR Uva Niagara",
    category: "",
    price: 12.0,
    unit: "kg",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 49,
    name: "Goiaba Vermelha",
    category: "",
    price: 0.99,
    unit: "kg",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 50,
    name: "Pera Importada",
    category: "",
    price: 7.99,
    unit: "kg",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 51,
    name: "Kiwi",
    category: "",
    price: 15.0,
    unit: "cumbuca",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 52,
    name: "Pera Williams",
    category: "",
    price: 9.99,
    unit: "kg",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 53,
    name: "Laranja Pêra",
    category: "",
    price: 2.99,
    unit: "kg",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 54,
    name: "Caqui Fuyu",
    category: "",
    price: 7.99,
    unit: "kg",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 55,
    name: "Laranja Lima",
    category: "",
    price: 7.99,
    unit: "kg",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 56,
    name: "Pera Williams",
    category: "",
    price: 9.99,
    unit: "kg",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 57,
    name: "Limão Taití",
    category: "",
    price: 4.99,
    unit: "kg",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 58,
    name: "Uva Vitória (s/ semente)",
    category: "",
    price: 10.0,
    unit: "cumbuca",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 59,
    name: "Limão Cravo",
    category: "",
    price: 4.99,
    unit: "kg",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 60,
    name: "Laranja bahia",
    category: "",
    price: 9.99,
    unit: "kg",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 61,
    name: "Tomate Cereja",
    category: "",
    price: 15.0,
    unit: "kg",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 62,
    name: "/",
    category: "",
    price: 6.0,
    unit: "pacote",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 63,
    name: "Maça Red",
    category: "",
    price: 15.0,
    unit: "kg",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 64,
    name: "Uva com Semente",
    category: "",
    price: 18.0,
    unit: "kg",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 65,
    name: "Maçã Gala",
    category: "",
    price: 9.99,
    unit: "kg",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 66,
    name: "Melancia",
    category: "",
    price: 20.0,
    unit: "cada",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 67,
    name: "Maça Fuji",
    category: "",
    price: 15.0,
    unit: "kg",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 68,
    name: "Atemoia",
    category: "",
    price: 15.0,
    unit: "kg",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 69,
    name: "Mamão Formosa A CONFIRMAR Uva com Semente isabel",
    category: "",
    price: 12.0,
    unit: "kg",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 70,
    name: "Mamão Papaya",
    category: "",
    price: 2.0,
    unit: "cada",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 71,
    name: "REAIS Manga Palmer",
    category: "",
    price: 7.99,
    unit: "kg",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 72,
    name: "Abacate",
    category: "",
    price: 6.99,
    unit: "kg",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 73,
    name: "Manga Tommy",
    category: "",
    price: 7.99,
    unit: "kg",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 74,
    name: "unid",
    category: "",
    price: 28.0,
    unit: "bandeja",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 75,
    name: "Cebolinha",
    category: "",
    price: 4.0,
    unit: "maço",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 76,
    name: "unid",
    category: "",
    price: 7.5,
    unit: "bandeja",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 77,
    name: "Coentro c/ Cebolinha",
    category: "",
    price: 5.0,
    unit: "maço",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 78,
    name: "KG",
    category: "",
    price: 12.0,
    unit: "pacote",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 79,
    name: "Salsinha c/ Cebolinha",
    category: "",
    price: 4.0,
    unit: "maço",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 80,
    name: "Temperos a Granel Diversos SOLICITAR A COTAÇÃO",
    category: "",
    price: 1.0,
    unit: "maço",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 81,
    name: "ml",
    category: "",
    price: 14.0,
    unit: "cada",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 82,
    name: "ml",
    category: "",
    price: 12.0,
    unit: "cada",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 83,
    name: "Manjericão",
    category: "",
    price: 2.5,
    unit: "maço",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 84,
    name: "ml",
    category: "",
    price: 32.0,
    unit: "cada",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 85,
    name: "Tomilho SOB ENCOMENDA Xarope da Vovó",
    category: "",
    price: 12.0,
    unit: "cada",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
  {
    id: 86,
    name: "Salsão A CONFIRMAR",
    category: "",
    price: 4.5,
    unit: "cada",
    defaultQuantity: 1,
    image: "",
    stock: 100,
  },
];
